// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMR2y7hU0uldIeQf7VBZrqvo3W7byRdIg',
    appId: '1:446932118516:web:732db7f4ce741c5c7667a1',
    messagingSenderId: '446932118516',
    projectId: 'finance-app-a38df',
    authDomain: 'finance-app-a38df.firebaseapp.com',
    storageBucket: 'finance-app-a38df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsPQCpFgfQQ7Dn87AAkadeWvfe55SPyFU',
    appId: '1:446932118516:android:785bc577b386822f7667a1',
    messagingSenderId: '446932118516',
    projectId: 'finance-app-a38df',
    storageBucket: 'finance-app-a38df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS4ymbA5YS756TIFEimSv0RC4qKSIeaCY',
    appId: '1:446932118516:ios:399cb733e5085b2c7667a1',
    messagingSenderId: '446932118516',
    projectId: 'finance-app-a38df',
    storageBucket: 'finance-app-a38df.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS4ymbA5YS756TIFEimSv0RC4qKSIeaCY',
    appId: '1:446932118516:ios:399cb733e5085b2c7667a1',
    messagingSenderId: '446932118516',
    projectId: 'finance-app-a38df',
    storageBucket: 'finance-app-a38df.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.finance',
  );
}
